/**
 * Build characters.seed.json from a curated character list (data/characters.input.json).
 * Uses TMDB only for genre tags and poster images. Blurbs are generated by llama-3.3-70b
 * from the model's own knowledge of each character — no plot overview needed.
 *
 * Usage:
 *   TMDB_API_KEY=xxx CLOUDFLARE_API_TOKEN=xxx CLOUDFLARE_ACCOUNT_ID=xxx node scripts/build-catalog.mjs
 *   node scripts/build-catalog.mjs --reblurbs-only   # regenerate blurbs from existing seed (no TMDB)
 */

import { writeFile, copyFile, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SEED_PATH = join(ROOT, "data/characters.seed.json");
const INPUT_PATH = join(ROOT, "data/characters.input.json");

const CF_API_TOKEN = process.env.CLOUDFLARE_API_TOKEN;
const CF_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID;
const WORKERS_AI_LLM = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";

const TMDB_BASE = "https://api.themoviedb.org/3";

/** Map TMDB genre ids to Archetype catalog genres */
const MOVIE_GENRE_MAP = {
  28: "Action",
  12: "Action",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Drama",
  18: "Drama",
  10751: "Drama",
  14: "Fantasy",
  36: "Historical",
  27: "Horror",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  53: "Thriller",
  10752: "Historical",
  37: "Historical",
};

const TV_GENRE_MAP = {
  10759: "Action",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Drama",
  18: "Drama",
  10751: "Drama",
  10762: "Drama",
  9648: "Mystery",
  10765: "Fantasy",
  10766: "Romance",
  10768: "Historical",
};

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function stableId(characterName, workTitle) {
  const hash = createHash("sha1")
    .update(`${workTitle}|${characterName}`)
    .digest("hex")
    .slice(0, 12);
  return `char-${hash}`;
}

function mapGenres(workType, genreIds) {
  const map = workType === "tv" ? TV_GENRE_MAP : MOVIE_GENRE_MAP;
  const out = [];
  for (const id of genreIds ?? []) {
    const g = map[id];
    if (g && !out.includes(g)) out.push(g);
  }
  if (out.length === 0) out.push("Drama");
  return out.slice(0, 4);
}

async function tmdb(path, apiKey) {
  const url = `${TMDB_BASE}${path}${path.includes("?") ? "&" : "?"}api_key=${apiKey}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`TMDB ${path}: ${res.status}`);
  return res.json();
}

// Search TMDB for a title to get genre IDs and poster image.
async function searchTitle(apiKey, workTitle, workType) {
  const kind = workType === "tv" ? "tv" : "movie";
  const path = `/search/${kind}?query=${encodeURIComponent(workTitle)}&language=en-US&page=1`;
  const data = await tmdb(path, apiKey);
  const result = data.results?.[0];
  if (!result) return null;
  const posterPath = result.poster_path ?? result.backdrop_path ?? null;
  return {
    genreIds: result.genre_ids ?? [],
    imageUrl: posterPath ? `https://image.tmdb.org/t/p/w342${posterPath}` : null,
  };
}

// Generate a personality blurb from the model's own knowledge of the character.
async function generateBlurb({ characterName, workTitle, workType, genres }) {
  const genreHint = genres.join(", ");
  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run/${WORKERS_AI_LLM}`,
    {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${CF_API_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messages: [
          {
            role: "system",
            content:
              "You write dense, trait-focused character descriptions for a film/TV personality matching system. " +
              "Draw on your knowledge of the character — do not invent or guess if you are uncertain. " +
              "Output only the description: no labels, no character name, no title. Present tense, third person.",
          },
          {
            role: "user",
            content:
              `Character: ${characterName}\n` +
              `Title: ${workTitle} (${workType})\n` +
              `Genre: ${genreHint}\n\n` +
              "Write 3-5 sentences about this character's personality based on your knowledge of them. " +
              "Focus on: core drive or motivation, behavior under pressure, relational style, and inner conflict. " +
              "If you are not familiar with this specific character, write based on their likely role in this genre and title. " +
              "Do NOT name the character or title. Do NOT summarize plot.",
          },
        ],
        max_tokens: 250,
      }),
    }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Workers AI ${res.status}: ${body.slice(0, 200)}`);
  }

  const data = await res.json();
  const text = data?.result?.response?.trim();
  if (!text) throw new Error("Empty response from Workers AI");
  return text;
}

function requireCFCredentials() {
  if (!CF_API_TOKEN || !CF_ACCOUNT_ID) {
    console.error("CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID are required for LLM blurb generation.");
    process.exit(1);
  }
}

// Regenerate blurbs for existing seed entries without re-fetching TMDB
async function reblurbsOnly() {
  requireCFCredentials();
  const raw = await readFile(SEED_PATH, "utf8");
  const rows = JSON.parse(raw);
  if (!Array.isArray(rows)) throw new Error("characters.seed.json must be a JSON array");

  const merged = [];
  const batchSize = 10;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const results = await Promise.all(
      batch.map(async (row) => ({
        ...row,
        blurb: await generateBlurb({
          characterName: row.characterName,
          workTitle: row.workTitle,
          workType: row.workType,
          genres: row.genres,
        }),
      }))
    );
    merged.push(...results);
    console.log(`  Blurbs: ${merged.length}/${rows.length}`);
  }

  const backupPath = join(ROOT, `data/characters.seed.backup.${Date.now()}.json`);
  try {
    await copyFile(SEED_PATH, backupPath);
    console.log(`Backup: ${backupPath}`);
  } catch (e) {
    if (e?.code !== "ENOENT") throw e;
  }
  await writeFile(SEED_PATH, JSON.stringify(merged, null, 2) + "\n", "utf8");
  console.log(`Rebuilt blurbs for ${merged.length} rows (--reblurbs-only).`);
}

async function main() {
  requireCFCredentials();
  const apiKey = process.env.TMDB_API_KEY;
  if (!apiKey) {
    console.error("Set TMDB_API_KEY (see https://www.themoviedb.org/settings/api)");
    process.exit(1);
  }

  const inputRaw = await readFile(INPUT_PATH, "utf8");
  const inputList = JSON.parse(inputRaw);
  if (!Array.isArray(inputList)) throw new Error("characters.input.json must be a JSON array");

  console.log(`Building catalog from ${inputList.length} curated characters...`);

  // Deduplicate
  const seen = new Set();
  const unique = inputList.filter(({ characterName, workTitle }) => {
    const key = `${workTitle.trim().toLowerCase()}|${characterName.trim().toLowerCase()}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  const tmdbCache = new Map();
  async function getTmdbMeta(workTitle, workType) {
    const key = `${workType}|${workTitle}`;
    if (tmdbCache.has(key)) return tmdbCache.get(key);
    try {
      const meta = await searchTitle(apiKey, workTitle, workType);
      await sleep(80);
      tmdbCache.set(key, meta);
      return meta;
    } catch (e) {
      console.warn(`  TMDB search failed for "${workTitle}": ${e.message}`);
      tmdbCache.set(key, null);
      return null;
    }
  }

  // Process in batches: fetch TMDB per title, generate blurb in parallel per batch
  const rows = [];
  const batchSize = 8;
  for (let i = 0; i < unique.length; i += batchSize) {
    const batch = unique.slice(i, i + batchSize);
    const batchRows = await Promise.all(
      batch.map(async ({ characterName, workTitle, workType }) => {
        const meta = await getTmdbMeta(workTitle, workType);
        const genreIds = meta?.genreIds ?? [];
        const genres = mapGenres(workType, genreIds);
        const imageUrl =
          meta?.imageUrl ??
          `https://placehold.co/320x480/1a1625/e8e0f2/png?font=montserrat&text=${encodeURIComponent(characterName.slice(0, 40))}`;

        const blurb = await generateBlurb({ characterName, workTitle, workType, genres });

        return {
          id: stableId(characterName, workTitle),
          workTitle,
          workType,
          characterName,
          blurb,
          genres,
          imageUrl,
        };
      })
    );
    rows.push(...batchRows);
    console.log(`  ${rows.length}/${unique.length} characters processed`);
  }

  const backupPath = join(ROOT, `data/characters.seed.backup.${Date.now()}.json`);
  try {
    await copyFile(SEED_PATH, backupPath);
    console.log(`Backup: ${backupPath}`);
  } catch (e) {
    if (e?.code !== "ENOENT") throw e;
  }
  await writeFile(SEED_PATH, JSON.stringify(rows, null, 2) + "\n", "utf8");
  console.log(`Wrote ${rows.length} characters to seed.`);
}

const run = process.argv.includes("--reblurbs-only") ? reblurbsOnly : main;
run().catch((e) => {
  console.error(e);
  process.exit(1);
});
